Notice there is no "/255.0" in line 82 in load_data.py to deal with version compatibility of imageio
